### ISSUE TITLE
UTF-8 character for submit element not supported on many systems

### ISSUE THREAD

**Issue by mr-z-ro** [eduardotkoller/convForm#17]
First off, thank you for this incredible library! Very cool work, that while perhaps obvious now that it's done, clearly took some ingenuity and hard work to get it to the elegant state it's in. Anyway, I have a minor issue to raise:

Currently the submit button uses "[Black Medium Right-Pointing Triangle Centred](https://www.utf8icons.com/character/11208/UTF-8-character)" as the value. Unfortunately, this is not supported on some systems which results in the classic "empty square of death" as shown here:

<img width="480" alt="screen shot 2018-02-22 at 2 33 46 pm" src="https://user-images.githubusercontent.com/1473877/36559946-698d4ed6-17dd-11e8-9b9d-401e26c59006.png">

I've replaced with "[Black Right-Pointing Triangle](https://www.utf8icons.com/character/9654/black-right-pointing-triangle)" for my implementation, which seems to be much more widely supported.

I'd have submitted a pull request to update this (e.g. on lines 261, 264 of `dist/jquery.convform.js`), but figured I'd submit as an issue instead, since it occurs in the minified js and perhaps other places as well.

**Comment by msgrasser** [comment]
I see this can otherwise be handled with some clever use of the `buttonClassStyle` option. Perhaps a `buttonText` option could be a consistent way to allow swapping in of a different value for the submit button?

**Comment by eduardotkoller** [comment]
Hello @mr-z-ro ,

Sorry that I took so long, I couldn't find time to look at this before. I'm really glad you like the plugin! It started as a fun experiment and ended up being more than that. 

I changed the triangle to the one you suggested, and added an option (buttonText) to allow the user to change the text on the button.

Thanks for the heads up!
