### ISSUE TITLE
Link to external website

### ISSUE THREAD

**Issue by provalone** [eduardotkoller/convForm#2]
I'd like to use some URL in the replay of the conversation, is it possible?
Something like this:
```
<select conv-question="Go searching ... ">
	<option value="www.google.com">Google</option>
	<option value="www.bing.com">Bing</option>
</select>
```
Thanks :)

**Comment by eduardotkoller** [comment]
I'm planning to add a callback option to answers on select, so you can call a custom function when the user clicks on an option (to redirect the user to a different URL, like in your case, or even implement something along the lines of social network login). As soon as I have some free time I'll implement it.

**Comment by eduardotkoller** [comment]
This feature was added in the last commit, and the readme was updated with examples.

**Comment by provalone** [comment]
Thank you 🥇
