### ISSUE TITLE
how to add images in the conversation?

### ISSUE THREAD

**Issue by louisloio** [eduardotkoller/convForm#21]
hi Team,
firstly thanks very much for your work it's very nice 
basically Im not a dev and I can use your script without difficulty

just one thing is missing for me. the robot is not able to send message with images.

did I miss something or it s not possible?

thanks
Louis

**Comment by louisloio** [comment]
hi I fixed it with this method

<input type="text" conv-question="<img width='300' src='assets/images.png'/>" no-answer="true">

in src= remove " and replace by  '

**Comment by eduardotkoller** [comment]
Hi Louis,
I didn't actively add support for images but it can work if you do like you described. I may add real support to this in the future.
