### ISSUE TITLE
W3C validation broken 

### ISSUE THREAD

**Issue by Xi-Flex** [eduardotkoller/convForm#23]
Hello, 
Great plugin !

The w3C validation is broken because the plugin use custom attribut. 
Do you think it's possible to replace custom attribut like 'conv-question' by data attribut?

Thanks!

**Comment by eduardotkoller** [comment]
All attributes used in the plugin now must begin with 'data-'. conv-question is now 'data-conv-question' for example. Readme updated.

**Comment by Xi-Flex** [comment]
Great! Thanks a lot!
