### ISSUE TITLE
Another question about nested forks

### ISSUE THREAD

**Issue by scionny** [eduardotkoller/convForm#25]
Hi, I'm having some trouble working with nested _conv-fork_. 

Here's my example, assuming I chose false in the next select:

```
<select name="accompanied" conv-question="¿Tienes pensado pedir la hipoteca solo o acompañado? ">
    <option value="false">Solo</option>
    <option value="true">Acompañado</option>
</select>
<div conv-fork="accompanied">
    <div conv-case="false" class="alone">
        ...
    </div>
    <div conv-case="true" class="alone">
        ...
    </div>
</div>
```

Then after that, I have the next code:

```
<select name="selectedProperty" conv-question="¿La casa ha sido elegida? ">
    <option value="true">Sí</option>
    <option value="false">No</option>
</select>
<!-- selected Properties -->
<div conv-fork="selectedProperty">
    <div conv-case="false">
        <div conv-fork="accompanied">
            <div conv-case="false">
                <!-- purchaseAmount -->
                <input type="number" pattern="^(0|[1-9][0-9]*)$" name="purchaseAmount"  conv-question=" true false">
            </div>
            <div conv-case="true">
                <!-- purchaseAmount -->
                <input type="number" pattern="^(0|[1-9][0-9]*)$" name="purchaseAmount"  conv-question=" true true">
            </div>
        </div>
    </div>
    <div conv-case="true">
        <div conv-fork="accompanied">
            <div conv-case="false">
                <!-- purchaseAmount -->
                <input type="number" pattern="^(0|[1-9][0-9]*)$" name="purchaseAmount"  conv-question=" false false">
            </div>
            <div conv-case="true">
                <!-- purchaseAmount -->
                <input type="number" pattern="^(0|[1-9][0-9]*)$" name="purchaseAmount"  conv-question=" false true">
            </div>
        </div>
    </div>
</div>
```

The thing is, at the conv-fork of "selectedProperty", it prints both conv-case divs (and only one of the inner "accompanied" forks). 

I have named the questions so I know wich child is being printed in order to debug. 

When you select "true" at the "selectedProperty" field, the conv-question is: _true false_. After you input some value, it asks again: _false false_, and I think it shouldn't.

Am I doing something wrong? Is it a bug?

Thanks !

**Comment by eduardotkoller** [comment]
The way the plugin is built it only forks the conversation exactly after the question, like a road into an intersection. Unfortunely because of this, you can't ask two questions in a row and nest-fork after, you must fork after the first one, ask the second question and fork again based on that. I know this leads to a lot of repeated code in the HTML but there isn't a way to make this simpler without recoding the plugin entirely. Sorry for the delay in answering.

**Comment by scionny** [comment]
That was very helpful, thank you sir!
