### ISSUE TITLE
Can't sent multiple answers with select options

### ISSUE THREAD

**Issue by lsigabygaby** [eduardotkoller/convForm#27]
Hello! I have a problem with the mutiple select, when I'm filling out the form it detects all the ones I activated, but when my PHP is executed, only sent the last option selected .... any sendmail.php that you recommend? or some rule that I should add to mine? .... BTW, I know about HTML and CSS, but I do not have much experience in PHP and JS.

**Comment by eduardotkoller** [comment]
Hello there!

For multiple selects to work in PHP, your input name must have [] in the end of its name. Do your select name has It?
