### ISSUE TITLE
Add dynamically questions in javascript

### ISSUE THREAD

**Issue by Etter** [eduardotkoller/convForm#28]
Hello,
Thanks for your library its great.
I wont to use your library to working with a chatBot.
It is possible to add dynamically questions into convForm in JS ?

Thanks for the answer.

**Comment by eduardotkoller** [comment]
This is not directly supported by the plugin, but you can do it using
callback functions to alter the 'next' attribute of the current state to
point to another state that you built yourself. As the states works like a
linked list, you must remember to build all the next states too, or link to
one of the previously built.

If you look at the code on my example chat, the callback functions and
logic that I use to "rollback" to a question can be used to add a question
dynamically, but as I said before, you will need to build the states object
manually (I generate all the states based on the input and select tags in a
form).

As you are not the first user to ask this, I may add a function to do this.

Em qua, 4 de jul de 2018 às 06:47, i-Shoot <notifications@github.com>
escreveu:

**Comment by Etter** [comment]
ok, Thanks for the answer

**Comment by eduardotkoller** [comment]
Hi again,

I just pushed a change that supports this. Take a look at the api_example.html in the last commit.

Cya!
