### ISSUE TITLE
New features :

### ISSUE THREAD

**Issue by fas3r** [eduardotkoller/convForm#34]
Hello @eduardotkoller , 

I did extensive changes to your plugins, such as : 

- including google map;
- handle 'hidden' input field;
- handle repetitive steps; 
-  new validation method including remote (AJAX); 
- ... 

Would you be interested by such changes ?  

Br, 
fas3r

**Comment by datrix88** [comment]
Hi @fas3r,
I'm very interested to new feauters.
Can you create a fork with your features?

Thanks.

**Comment by eduardotkoller** [comment]
@fas3r Hello,

I am interested too. Can you create a fork or a merge request?

**Comment by fas3r** [comment]
Hello, 

I started to comment the code as there were a lot of changes, I will try to submit the request beginning of october.
