### ISSUE TITLE
Re Building States [ Not Working ]

### ISSUE THREAD

**Issue by praveenyadv** [eduardotkoller/convForm#36]
![gittt](https://user-images.githubusercontent.com/13960560/46416506-4939dd80-c745-11e8-83a6-a74d2206da45.PNG)

I saved all the inputs in a global array (access) and i wrote this callback

function jump(stateWrapper) {
	var singleState = new SingleConvState(access[0]);
	stateWrapper.current.next = singleState;
	for(var i in access) {
        if(i != 0 && access.hasOwnProperty(i)){
            singleState.next = new SingleConvState(access[i]);
            singleState = singleState.next;
        }
    }
	console.log("Calling jump");
}

this is working but sometimes the questions and it's order are not correct,  the questions comes randomly sometimes even though i m building all the states again can u please help me fix this?

**Comment by eduardotkoller** [comment]
Hi,

I cant really help you without more info.

Can you log the inputs global array and the order of the questions
displayed? How are you building this global array?

**Comment by praveenyadv** [comment]
Hi,

I defined an empty global array at the top of the script and after building all the input values in a inputs array, i m assigning this to the global array i created.

so that all the inputs are saved globally in the same order as when they were first initialized and if i console.log that global array i can see all the input values as array with correct order in console window but when i use that array to call change the function sometimes it shows random questions.
i think the issue is in fork and case.

u can see my code here: https://gist.github.com/praveenyadv/d50d5f14963245c8e17c68e078a71b48

**Comment by praveenyadv** [comment]
Hi,

I defined an empty global array at the top of the script and after building all the input values in a inputs array, i m assigning this to the global array i created.

so that all the inputs are saved globally in the same order as when they were first initialized and if i console.log that global array i can see all the input values as array with correct order in console window but when i use that array to call change the function sometimes it shows random questions.
i think the issue is in fork and case.

u can see my code here: https://gist.github.com/praveenyadv/d50d5f14963245c8e17c68e078a71b48

**Comment by eduardotkoller** [comment]
Hi, sorry for the delay

Can you try this the same way I do on my example in the demo (callback that rollbacks to the programmer question, in the lines 88-105 in the index.html), instead of rebuilding all the states from inputs?

Also, if you want to have more freedom in your program logic, try using the API example (it doesn't need to use an API, but you can construct the states on the fly based on the user's answers).
