### ISSUE TITLE
Visual problem with firefox

### ISSUE THREAD

**Issue by EricB91** [eduardotkoller/convForm#39]
Hi Eduardo,

Thanks a lot for your awesome job with this script.

A noticed a small visual artefact using firefox : when form is long enough, select options are overlapping the question.

Any help ?

![image](https://user-images.githubusercontent.com/45387558/49076126-99f71f80-f238-11e8-93bc-ddb046913007.png)

**Comment by eduardotkoller** [comment]
Well, this is strange, the plugin adds a padding in the chat exactly for this, and for some reason in firefox it doesn't. I can't look into this right now, but I suspect that if I change the padding to margin, it might work. I'll look into this when I get home.
