### ISSUE TITLE
Firefox scroll bar not hidden

### ISSUE THREAD

**Issue by provalone** [eduardotkoller/convForm#4]
On Firefox scroll bar is visible. No Effect on IE and Chrome.

![firefox_scroll_bar](https://cloud.githubusercontent.com/assets/28945647/26775842/f9076d06-49d6-11e7-9ac4-9b3113a1e8f0.png)

**Comment by eduardotkoller** [comment]
Mozilla doesn't allow removing the scrollbars like chrome/safari. I don't have the time to fix this at the moment, but if you want to look into it, you can try adding `margin-right: -14px` to the containers that are showing the scrollbar.
