### ISSUE TITLE
Disappearing chat box

### ISSUE THREAD

**Issue by njones-sri** [eduardotkoller/convForm#42]
Commit 23275cf3296dab575c94c67cb21db3af0b69bf3a  seems to eat the chatbox if the user filters a select box. On the demo page, if you just type in 'Y' 'E' and then alternate between 'S' and backspace, the message box disappears until it is just the buttons.

**Comment by eduardotkoller** [comment]
Sorry for the long delay in fixing this. Last commit d87f0642ff002b724b709c125d3e52943eebcdc6 pushed a fix.
