### ISSUE TITLE
Autocomplete Feature/ Text input with suggestions

### ISSUE THREAD

**Issue by abhi09cse02** [eduardotkoller/convForm#44]
I want to create A Smart Chat Bot From An Html Form - convForm by referring given url with autocomplete feature to suggest city/town name. How can i use it? Please suggest to write Text input with suggestions.

https://eduardotkoller.github.io/convForm/

**Comment by eduardotkoller** [comment]
There is no way to do auto-complete or suggestions at the moment. I might add this in the future but I don't have enough time to work on this right now and therefore can't promise it. Sorry.
