### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by Divyatva** [eduardotkoller/convForm#45]
Hello,

After clicking no option, all questions show, but after selecting next question script stop working.

**Comment by eduardotkoller** [comment]
Hi there, I need more info on this. This error means there is probably some infinite recursive call somewhere. Are you using custom callback functions? Can you tell me with more details what you did to cause the error?

**Comment by Divyatva** [comment]
Step1: select any question
Step2: click on No option
Step2: now select another question

Script stop working

**Comment by eduardotkoller** [comment]
What do you mean by "select any question"?  You can't "select a question" so my guess is you mean "select any answer"?

Also, can you reproduce the bug within the demo? 

If not, I can't help you without the code you are working on.
