### ISSUE TITLE
Send multiple messages between agent and user

### ISSUE THREAD

**Issue by User0123456789** [eduardotkoller/convForm#48]
Hello, how to send multiple messages between agent and user? Like, the user can send multiple messages chat after he/she sent the first message (vice versa - agent side) even the agent is not yet answer the chat. And if the user did not type and send anything within 5 minutes, the chat will ended.

How to do this? Please help me. Thank you

Here's the current code:

```
success: function (data) {
								original = convState.current;
								convState.current.next = convState.newState({
									type: 'text',
									questions: [data.messages],
								});

								convState.current.next.next = convState.newState({
									type: 'text',
									questions: [data.messages],
									answers: $('input[type=text]#chatConcern').val()
								});
										
								setTimeout(ready, Math.random() * 500 + 100);
							}
```

**Comment by eduardotkoller** [comment]
Hi there. There is no way to do that at the moment, sorry. The chat is built to be synchronous in the conversation state - one person talks at a time. It would need a rebuild of the code to make this work.
