### ISSUE TITLE
Can I send some input from Chat Bot to my mail

### ISSUE THREAD

**Issue by kshyam1795** [eduardotkoller/convForm#56]
hii,

Actually i used POST method but this is not working so i have use GET method and got the data from chat bot form but the mail function is not working. Please help me.

thanks 

## This is my chat bot form
`<form action="send_form_email.php" method="GET" class="hidden" id="">
                                                    <input type="text" name="name" data-conv-question="Welcome to Citiyano De Solution. Please provide your name.|Okay! Please, tell me your name first.">
                                                    <input type="text" data-conv-question="Hello, {name}:0! It's a pleasure to meet you." data-no-answer="true">
                                                    <input type="text" data-conv-question="What kind of service do you like?" data-no-answer="true">
                                                      <select name="multi[]" data-conv-question="Our services are:" multiple>
                                                          <option value="IT & E-Governance">IT</option>
                                                          <option value="Human Resource">HR</option><br>
                                                          <option value="Urban Planning">Urban Planning </option>
                                                      </select>
                                                    <input type="text" data-conv-question="Please provide your Email id" data-no-answer="true">
                                                    <input data-conv-question="" data-pattern="^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"  id="email" type="email" name="email" required placeholder="What's your e-mail?">
                                                      <select  data-conv-question="Thanks for choosing Citiyano De Solution, We are currently offline. We will contact you shortly." id=" userInput">
                                                         <option value="" callback="submit">Awesome!</option>
                                                      </select>		
                                                </form>`

## This is my mail Script 
`<?php
	
	
	if(isset($_GET['email']) && !empty($_GET['email']))
   {
    $emailAddress = $_GET['email'];
    }

    if(isset($_GET['name']) && !empty($_GET['name'])){
    $name= $_GET['name'];
    }
	if(isset($_GET['multi[]']) && !empty($_GET['multi[]'])){
    $multi= $_GET['multi[]'];
    }

		$to      = 'abc@.def.com';
        $subject = 'Received from Chat bot';
        $message = 'hii ' . $name;
        $headers = 'From: abc@.def.com' . "\r\n" .
            'Reply-To: kshyam1795@gmail.com' ;
		/*$htmlContent = '<h2>Received from Chat bot</h2>
                    <p><b>Name:</b> '.$name.'</p>
                    <p><b>Email:</b> '.$from.'</p>
                    <p><b>Position:</b> '.$subject.'</p>
					<p><b>Message:</b><br/>'.$message.'</p>';*/
		
		$result=mail($to, $subject, $message, $headers, $multi);
        if(!$result)
        {
            die('There was an error sending out the email');
        }
	//header('Location:index.php');
?>
   `

**Comment by eduardotkoller** [comment]
Hi, sorry for the long delay. I am closing the issue because this is not related to the plugin itself, so I can't really help you.

 `mail` function in php is not a good idea and mostly certainly will not work because email services will reject the email. You have to use email services like Amazon SES, SendGrid, etc.
