### ISSUE TITLE
Dynamically adding  answers [from] filling into a custom form

### ISSUE THREAD

**Issue by Gigiart** [eduardotkoller/convForm#59]
How can I insert a user answer after filling a form from the dialog?

I have this question: "Please add your full details" -> Yes/ No. If Yes -> callback a function that opens a dialog form.

I was able to render the result as a bot question with no answer,  but I want the result of that form to be rendered as an answer from the user. Any idea how can I do that.

Thanks a lot for this plugin!

**Comment by eduardotkoller** [comment]
Hi there, sorry for the delay. As I said on the README, I can't maintain this anymore.

I can't really seem to understand what you need here. You can make select options call custom callback functions, and you can even use this to change the dialog, next questions, answer from the user, and basically anything. Callback functions pass the state machine underlying the logic and you can edit it the way you want.

If you want to know more, see #62 .
