### ISSUE TITLE
Nested forks/multiple forks

### ISSUE THREAD

**Issue by chrisjelerang** [eduardotkoller/convForm#6]
Hi, Loving the plugin. Quick question. Does it support nested forks and multiple forks?

**Comment by eduardotkoller** [comment]
Yes, It supports nested forks. I tested it and it had a simple bug, now it's fixed. Thanks for the heads up.

**Comment by chrisjelerang** [comment]
Thanks for clarifying & fixing. I'll give it a go and let you know.
