### ISSUE TITLE
Reload Function

### ISSUE THREAD

**Issue by Rocosochico** [eduardotkoller/convForm#8]
Hello friend
First of all, thank you very much for share you nice plugin.
I would like to know how to do it for example if I want to start again once the chat has already started or finished.
Can you help me please.

**Comment by eduardotkoller** [comment]
Hello friend,
Thanks, I appreciate!

If you want to reload the conversation and start again, without reloading the page, I'm sorry, I didn't made the plugin thinking of using it like this, so the plugin itself doesn't give you any ways to do that. 

But, you can make it work using jQuery. Just delete the entire convForm generated by the plugin from the page, insert new inputs and call the convForm function again.
